services:
  ros:
    image: abmhamdi/ros2
    privileged: true
    network_mode: "host"
    devices:
      - /dev/dri
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true  # equivalent to -i
    tty: true         # equivalent to -t
